#!/bin/sh
#
# Starts ufo
#

NODE_MODULES=/usr/lib/node_modules
FOREVER=$NODE_MODULES/forever/bin/forever
PID_FILE=/var/run/ufo.pid
UFO_MAIN=$NODE_MODULES/ufo.rpi/ufo.js

start() {
	echo -n "Starting ufo: "
	$FOREVER start --pidFile $PID_FILE $UFO_MAIN
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping ufo: "
	$FOREVER stop `cat $PID_FILE`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
