#!/bin/sh
#
# Starts hostapd
#

start() {
	echo -n "Starting hostapd: "
	umask 077
	start-stop-daemon -S -q -b -p /var/run/hostapd.pid \
		--exec /usr/sbin/hostapd /etc/hostapd.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping hostapd: "
	start-stop-daemon -K -q -p /var/run/hostapd.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
